# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21.4

    - name: Build 01_1
      run: go build -v github.com/glennhartmann/aoc23/src/01_1

    - name: Build 01_2
      run: go build -v github.com/glennhartmann/aoc23/src/01_2
